masters:
  hosts:
    master1:
      ansible_user: vagrant
      ansible_host: 192.168.99.101
      ansible_ssh_private_key_file: ./.vagrant/machines/k8s-1Master-2Nodes-kubemaster1/virtualbox/private_key
    node1:
      ansible_user: vagrant
      ansible_host: 192.168.99.201
      ansible_ssh_private_key_file: ./.vagrant/machines/k8s-1Master-2Nodes-kubenode1/virtualbox/private_key
    node2:
      ansible_user: vagrant
      ansible_host: 192.168.99.202
      ansible_ssh_private_key_file: ./.vagrant/machines/k8s-1Master-2Nodes-kubenode2/virtualbox/private_key
