# -*- mode: ruby -*-
# vi:set ft=ruby sw=2 ts=2 sts=2:

# Define the number of master and worker nodes
# If this number is changed, remember to update setup-hosts.sh script with the new hosts IP details in /etc/hosts of each VM.
NUM_MASTER_NODE = 1
NUM_WORKER_NODE = 2

IP_NW = "192.168.99."
MASTER_IP_START = 100
NODE_IP_START = 200

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2004"
  config.vm.box_check_update = false

  # Provision Master Nodes
  (1..NUM_MASTER_NODE).each do |i|
    config.vm.define "k8s-1Master-2Nodes-kubemaster#{i}" do |master|
      # Name shown in the GUI
      master.vm.provider "virtualbox" do |vb|
        vb.name = "kubemaster#{i}"
        vb.memory = 2048
        vb.cpus = 2
      end
      master.vm.hostname = "kubemaster#{i}"
      master.vm.network :private_network, ip: IP_NW + "#{MASTER_IP_START + i}"
      master.vm.network "forwarded_port", guest: 22, host: "#{22221 + i}"
      config.vm.provision "shell", inline: <<-SHELL
        if [ ! -f /etc/kubernetes/kubelet.conf ]; then
          kubeadm init --pod-network-cidr 10.244.0.0/16 --apiserver-advertise-address=192.168.99.101;
          password=$(openssl rand -base64 32)
          useradd --home-dir /home/kubeuser --skel /etc/skel/ --create-home --password WCzxM3Qq5OChodHdv2B3R6vlOJcLiXkHZEYpXdusWeo= kubeuser
          su kubeuser --command="mkdir -p /home/kubeuser/.kube"
          cp -i /etc/kubernetes/admin.conf /home/kubeuser/.kube/config
          chown kubeuser:kubeuser /home/kubeuser/.kube/config
        fi
        cd /root && \
          curl https://docs.projectcalico.org/manifests/calico.yaml -O && \
          chown kubeuser:kubeuser calico.yaml
        su kubeuser --command="kubectl apply -f calico.yaml"
      SHELL
    end
  end

  # Provision Worker Nodes
  (1..NUM_WORKER_NODE).each do |i|
    config.vm.define "k8s-1Master-2Nodes-kubenode#{i}" do |node|
      node.vm.provider "virtualbox" do |vb|
        vb.name = "kubenode#{i}"
        vb.memory = 2048
        vb.cpus = 2
      end
      node.vm.hostname = "kubenode#{i}"
      node.vm.network :private_network, ip: IP_NW + "#{NODE_IP_START + i}"
      node.vm.network "forwarded_port", guest: 22, host: "#{22231 + i}"
    end
  end

  config.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get upgrade -y 

      awk -i inplace  '/^[^#](.*)[ \t]+none[ \t]+swap[ \t]+sw/ { print "#" $0; next; } { print; } ' /etc/fstab
      swapoff -a
  SHELL

  #config.vm.provision "shell", path: "install-docker.sh"
  config.vm.provision "shell", path: "install-kubeadm.sh"

end
