ubuntu:
  hosts:
    node:
      ansible_host: localhost
      ansible_user: vagrant 
      ansible_port: 2222
      ansible_ssh_private_key_file: /home/micki/workspace/go/src/github.com/MickiFoerster/vagrant/k8s-single-node/1.16/.vagrant/machines/k8s-single-node/virtualbox/private_key
