ubuntu:
  hosts:
    k8s-single-node-123:
      ansible_host: localhost
      ansible_user: vagrant 
      ansible_port: 2222
      ansible_ssh_private_key_file: /home/micki/workspace/go/src/github.com/MickiFoerster/vagrant/k8s-single-node/1.23/.vagrant/machines/k8s-single-node-123/virtualbox/private_key
